name: Update target data
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Update target data'
        required: false
  schedule:
    - cron: "20 16 * * 3"

jobs:
  update_target_data:
    if: github.repository_owner == 'cdcepi'
    runs-on: macOS-latest
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install dependencies
        run: |
          install.packages(c("cli", "dplyr", "here", "lubridate", "readr", "RSocrata", "tidyr"))
        shell: Rscript {0}
      - name: Generate target csv files
        run:  Rscript target-data/get_target_data.R
      - name: Generate Hubverse-formatted target-data
        run:  Rscript target-data/get_target_data_hubverse.R
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with: 
          add: 'target-data'
          message: "Update target data"
          default_author: github_actions
          push: true

